# add your sample (e.g., "strain_01") & reference (e.g., "ref_genome") names below

samples:
  - DTS-D-1
  - DTS-D-2
  - DTS-D-3

read_extension: "fastq.gz"
ref_assembly: "reference/ref_assembly.fasta"
ref_annotations: "reference/ref_annotations.gtf"
