# add your sample (e.g., "strain_01") & reference (e.g., "ref_genome") names below

samples:
  - DTS-S-1
  - DTS-S-2
  - DTS-S-3
  - DTS-W-1
  - DTS-W-2
  - DTS-W-3

conditions:
  test: [DTS-S-1, DTS-S-2, DTS-S-3]
  control: [DTS-W-1, DTS-W-2, DTS-W-3]

read_length: 150
strandedness: 0

read_extension: "fastq.gz"
outdir: "FASTQ/trimmed"
ref_assembly: "reference/ref_assembly.fasta"
ref_annotations: "reference/ref_annotations.gtf"
