cluster: "sbatch
    -p ceres
    -A gifvl
    --job-name={rule}
    --time={resources.runtime}
    --mem={resources.mem_mb}M
    --cpus-per-task={threads}
    -N 1
    -n 1
    -o logs/slurm/{rule}.%j.out
    -e logs/slurm/{rule}.%j.err"

default-resources:
  - mem_mb=8000
  - runtime="02:00:00"

jobs: 100
use-conda: true
restart-times: 1
latency-wait: 60
max-jobs-per-second: 5
